# Site
name: "Paulovich.NET"
title: "Software Architecture and .NET Development"
description: "Software Architecture and .NET Development"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
disqus: 'paulovichdotnet'
mailchimp-list: 'https://paulovich.us3.list-manage.com/subscribe/post?u=3908a479dc89ce5adc26cc8c5&amp;id=9275121da4'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ivanpaulovich:
    name: Ivan Paulovich
    display_name: Ivan Paulovich
    gravatar: 8821ecd598e75afc5f9f33eac6cabb0d
    email: ivan@paulovich.net
    web: https://paulovich.net
    twitter: https://twitter.com/ivanpaulovich
    description: "Agile .NET developer focused on Clean architecture. I enjoy implementing solutions based on use cases and decoupled from technology details."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]

include:
  - assets